# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: ed2ksum
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mipsle
    ignore:
      - goos: windows
        goarch: arm
        goarm: 6
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.gitRev="{{.ShortCommit}}" -X main.buildTime="{{.CommitDate}}"
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
      - ./dontoptimizeme=-N
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}

archives:
  -
    id: ed2ksum
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip



checksum:
  name_template: 'checksums.txt'
  algorithm: sha512
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'